version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Africa/Cairo
  open-pull-requests-limit: 10
  assignees:
  - rudotriton
  ignore:
  - dependency-name: stylelint
    versions:
    - 13.8.0
    - 13.9.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
