name: Lint
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: npx eslint src/
  merge:
    name: Merge pull requests
    runs-on: ubuntu-latest
    needs: label
    steps:
      - uses: pascalgn/automerge-action@v0.2.4
        env:
          GITHUB_TOKEN: 'pull requests'
