name: Lint src directory
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: npx eslint src/
  label:
    name: Autolabel
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: banyan/auto-label@master
        env:
          GITHUB_TOKEN: 'issues'
